""" added Foreign key constraint

Revision ID: 1fbf784ae007
Revises: e02ac9be4cc0
Create Date: 2026-09-12 17:49:31.791460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fbf784ae007'
down_revision: Union[str, Sequence[str], None] = 'e02ac9be4cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_posts_owner_id_fkey'), 'user_posts', 'users', ['owner_id'], ['id'])
    #op.create_foreign_key(op.f('users_id_fkey'), 'users', 'register_details', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_posts_owner_id_fkey'), 'user_posts', type_='foreignkey')
    op.drop_constraint(op.f('users_id_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###
