""" Added Some Changes to Database Schema

Revision ID: e02ac9be4cc0
Revises: 18ac708502c1
Create Date: 2026-09-12 16:43:04.212938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02ac9be4cc0'
down_revision: Union[str, Sequence[str], None] = '18ac708502c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register_details', sa.Column('role', sa.String(), nullable=False,server_default='user'))
    op.drop_constraint(op.f('register_details_user_id_fkey'), 'register_details', type_='foreignkey')
    op.drop_column('register_details', 'user_id')
    op.drop_column('user_posts', 'user_id')
    op.add_column('user_posts', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('user_posts_owner_id_fkey'), 'user_posts', 'users', ['owner_id'], ['id'])
    
    
    
    op.create_foreign_key(op.f('users_id_fkey'), 'users', 'register_details', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_id_fkey'), 'users', type_='foreignkey')
    op.add_column('user_posts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('user_posts_owner_id_fkey'), 'user_posts', type_='foreignkey')
    op.create_foreign_key(op.f('user_posts_user_id_fkey'), 'user_posts', 'users', ['user_id'], ['id'])
    op.drop_column('user_posts', 'owner_id')
    op.add_column('register_details', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('register_details_user_id_fkey'), 'register_details', 'users', ['user_id'], ['id'])
    op.drop_column('register_details', 'role')
    # ### end Alembic commands ###
